version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  frontend:
    build:
      context: ./apps/nuxt-app
      dockerfile: dockerfile
    container_name: nuxt
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nuxt-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  backend:
    build:
      context: ./apps/backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "3002:3002"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  frontend_angular:
    build:
      context: ./apps/angular-app
      dockerfile: dockerfile
    container_name: angular
    ports:
      - "4002:4002"
    volumes:
      - ./apps/angular-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # App connection (AMQP)
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ${
      }
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  minio_data:
  rabbitmq_data:
